// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDY4dvv2OUWllY3JStuCqlM_DAaMdnKd4',
    appId: '1:381148492179:web:b7fc3a8b2fc3adfb823866',
    messagingSenderId: '381148492179',
    projectId: 'legalease-d9c88',
    authDomain: 'legalease-d9c88.firebaseapp.com',
    storageBucket: 'legalease-d9c88.firebasestorage.app',
    measurementId: 'G-BZTK3YLZCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonmOOx9JV5kQ7Tq2AeAkEQPGTKzC3OBw',
    appId: '1:381148492179:android:6e4bbe7c8e925789823866',
    messagingSenderId: '381148492179',
    projectId: 'legalease-d9c88',
    storageBucket: 'legalease-d9c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXh_8DaYV06_gcxNi-2u1yLBzCCJ3k9hs',
    appId: '1:381148492179:ios:c5dabf86fe699803823866',
    messagingSenderId: '381148492179',
    projectId: 'legalease-d9c88',
    storageBucket: 'legalease-d9c88.firebasestorage.app',
    iosBundleId: 'com.example.legalease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXh_8DaYV06_gcxNi-2u1yLBzCCJ3k9hs',
    appId: '1:381148492179:ios:c5dabf86fe699803823866',
    messagingSenderId: '381148492179',
    projectId: 'legalease-d9c88',
    storageBucket: 'legalease-d9c88.firebasestorage.app',
    iosBundleId: 'com.example.legalease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDY4dvv2OUWllY3JStuCqlM_DAaMdnKd4',
    appId: '1:381148492179:web:8da66096fba32937823866',
    messagingSenderId: '381148492179',
    projectId: 'legalease-d9c88',
    authDomain: 'legalease-d9c88.firebaseapp.com',
    storageBucket: 'legalease-d9c88.firebasestorage.app',
    measurementId: 'G-98R6VXGGS0',
  );
}
